apiVersion: directory.googleworkspace.upbound.io/v1alpha1
kind: User
metadata:
  name: my-example-user
spec:
  forProvider:
    primaryEmail: "example.user@yourdomain.com"
    name:
      givenName: "Test"
      familyName: "User"

  providerConfigRef:
    name: default