apiVersion: group.googleworkspace.upbound.io/v1alpha1
kind: Resource
metadata:
  name: my-example-group
spec:
  forProvider:
    triggers:
      example-trigger: example-value
  providerConfigRef:
    name: default