/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AssignmentObservation struct {

	// The unique ID of the user this role is assigned to.
	AssignedTo *string `json:"assignedTo,omitempty" tf:"assigned_to,omitempty"`

	// ETag of the resource.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
	OrgUnitID *string `json:"orgUnitId,omitempty" tf:"org_unit_id,omitempty"`

	// The ID of the role that is assigned.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Defaults to `CUSTOMER`. The scope in which this role is assigned. Valid values are :
	// - `CUSTOMER`
	// - `ORG_UNIT`
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

type AssignmentParameters struct {

	// The unique ID of the user this role is assigned to.
	// +crossplane:generate:reference:type=User
	// +kubebuilder:validation:Optional
	AssignedTo *string `json:"assignedTo,omitempty" tf:"assigned_to,omitempty"`

	// Reference to a User to populate assignedTo.
	// +kubebuilder:validation:Optional
	AssignedToRef *v1.Reference `json:"assignedToRef,omitempty" tf:"-"`

	// Selector for a User to populate assignedTo.
	// +kubebuilder:validation:Optional
	AssignedToSelector *v1.Selector `json:"assignedToSelector,omitempty" tf:"-"`

	// If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
	// +crossplane:generate:reference:type=OrgUnit
	// +kubebuilder:validation:Optional
	OrgUnitID *string `json:"orgUnitId,omitempty" tf:"org_unit_id,omitempty"`

	// Reference to a OrgUnit to populate orgUnitId.
	// +kubebuilder:validation:Optional
	OrgUnitIDRef *v1.Reference `json:"orgUnitIdRef,omitempty" tf:"-"`

	// Selector for a OrgUnit to populate orgUnitId.
	// +kubebuilder:validation:Optional
	OrgUnitIDSelector *v1.Selector `json:"orgUnitIdSelector,omitempty" tf:"-"`

	// The ID of the role that is assigned.
	// +crossplane:generate:reference:type=Role
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v1.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v1.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// Defaults to `CUSTOMER`. The scope in which this role is assigned. Valid values are :
	// - `CUSTOMER`
	// - `ORG_UNIT`
	// +kubebuilder:validation:Optional
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

// AssignmentSpec defines the desired state of Assignment
type AssignmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AssignmentParameters `json:"forProvider"`
}

// AssignmentStatus defines the observed state of Assignment.
type AssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Assignment is the Schema for the Assignments API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,googleworkspace}
type Assignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AssignmentSpec   `json:"spec"`
	Status            AssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AssignmentList contains a list of Assignments
type AssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Assignment `json:"items"`
}

// Repository type metadata.
var (
	Assignment_Kind             = "Assignment"
	Assignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Assignment_Kind}.String()
	Assignment_KindAPIVersion   = Assignment_Kind + "." + CRDGroupVersion.String()
	Assignment_GroupVersionKind = CRDGroupVersion.WithKind(Assignment_Kind)
)

func init() {
	SchemeBuilder.Register(&Assignment{}, &AssignmentList{})
}
